-- ===================================================================
-- Quadax Real-Time Denial Prevention Engine - Database Setup
-- Run this first in Snowsight
-- ===================================================================

-- Create main database
CREATE OR REPLACE DATABASE QUADAX_DENIAL_PREVENTION;

-- Create schemas
CREATE OR REPLACE SCHEMA RAW_DATA 
COMMENT = 'Raw, unprocessed data from various sources';

CREATE OR REPLACE SCHEMA PROCESSED_DATA 
COMMENT = 'Cleaned and processed data ready for analytics';

CREATE OR REPLACE SCHEMA ANALYTICS 
COMMENT = 'Analytics views, aggregations, and derived datasets';

CREATE OR REPLACE SCHEMA ML_MODELS 
COMMENT = 'Machine learning models and predictions';

-- Create auto-scaling warehouses
CREATE OR REPLACE WAREHOUSE ML_TRAINING_WH WITH 
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Warehouse for ML model training workloads';

CREATE OR REPLACE WAREHOUSE REALTIME_PROCESSING_WH WITH 
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Warehouse for real-time claim processing';

CREATE OR REPLACE WAREHOUSE ANALYTICS_WH WITH 
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Warehouse for analytics and reporting workloads';

-- Set context
USE DATABASE QUADAX_DENIAL_PREVENTION;
USE WAREHOUSE ANALYTICS_WH;

-- Create file formats for data loading
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    COMPRESSION = 'AUTO';

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    IGNORE_UTF8_ERRORS = FALSE;

-- Grant permissions (adjust roles as needed for your organization)
GRANT USAGE ON DATABASE QUADAX_DENIAL_PREVENTION TO ROLE SYSADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE QUADAX_DENIAL_PREVENTION TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE QUADAX_DENIAL_PREVENTION TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE QUADAX_DENIAL_PREVENTION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE ML_TRAINING_WH TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE REALTIME_PROCESSING_WH TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE SYSADMIN;

-- Show created objects
SHOW DATABASES LIKE 'QUADAX_DENIAL_PREVENTION';
SHOW SCHEMAS IN DATABASE QUADAX_DENIAL_PREVENTION;
SHOW WAREHOUSES LIKE '%WH';

SELECT 'Database setup completed successfully!' as STATUS;
